Add utilities and tests
soc221b/namanager pull request #3
Opened 2018-03-08 13:54 UTC by iattempt

I added some useful functions and tests for it.

The import error it occurs when I use those commands below:
1. `nosetests .`
2. `flake8 .`
3. `python3 tests/test.py`
4. `python3 file_ckecker/file_ckecker.py`
It seems that because folder name file_checker is same as file_checker.py in the folder, and loader is ambiguous.

2018-03-08 15:16 UTC, arnavb requested changes

2018-03-08 15:16 UTC, arnavb commented on src/file_checker.py
> +            if format == 'upper_case':
I wouldn't use format as a name. It is a fairly common function that shouldn't cause any error here, but still.

2018-03-08 15:16 UTC, arnavb commented on tests/test.py
> +            errors += ["'{0}' is in '{1}'".format(gen_unique_str(s), s)]
I think using the `.push` function would be clearer here.

2018-03-08 15:16 UTC, arnavb commented on tests/test.py
> +        if errors:
I personally don't like the approach of throwing an exception if there are errors. Testing usually involves a series of asserts, and exceptions are meant for _exceptional_ behavior anyways.

2018-03-08 15:16 UTC, arnavb commented on tests/test.py
> +            for w in words:
I believe you can use a list comprehension for these internal loops.

2018-03-08 15:16 UTC, arnavb commented on tests/test.py
> +                        w = w[0].upper() + w[1:]
Ternary possible here.

2018-03-08 15:29 UTC, arnavb commented on src/util.py
> +        beg = s.find(re.search('[A-Za-z]', s)[0]) if len(s) else -1
Don't subscript. Use `.group(0)` to fix the bug.

2018-03-08 16:01 UTC, arnavb commented
@iattempt I was able to fix the grouping bug, but I am unsure how to fix the import problem you are getting.

2018-03-09 01:29 UTC, iattempt commented
@arnavb I have fixed the import error, to reproduce on these error:
1. `git checkout -b 8365364`
2. I want to use class FileChecker, and I try to add these code to tests/test.py:

    1. import `module` and call FileChecker by module-name
    ```python
    import file_checker # noqa

    fc = file_checker.FileChecker()
    ```

    2. from `module` import `name`
    ```python
    from file_checker import FileChecker# noqa
    ```

3. `nosetests .`

output:
`ImportError: cannot import name 'FileChecker'` or
`AttributeError: module 'file_checker' has no attribute 'FileChecker'`

2018-03-09 01:31 UTC, arnavb commented
@iattempt Alright, I'll look it over tomorrow!

2018-03-09 11:31 UTC, arnavb submitted a review, later dismissed

2018-03-09 13:25 UTC, arnavb commented
@iattempt I have found the solution to the import error. You are right, it is because of packages taking higher precedence over files. Since `file_checker` has an `__init__.py`, it takes higher precedence over the file inside. If you need to access the inner file, then follow the following steps:

1. Move all files in folder `src` to a new folder `file_checker`.
2. Change the respective line to:
    ```Python
    sys.path.append(os.sep.join([os.path.dirname(os.path.realpath(__file__)),
                             '..',
                             'file_checker'
                             ]))
    ```
3. Go to the topmost directory. (The one with `README.md`) and add an empty file `__init__.py`.
4. Run `nosetests . -v`

Output: 

```
test.TestFileChecker.test_convert_sep ... ok
This test is assumed that ... ok
test.TestUtil.test_gen_unique_str ... ok
test.TestUtil.test_get_first_word ... ok
test.TestUtil.test_get_words ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.433s

OK
```

However, this is _not_ recommended practice, as it involves extra files. The better solution is to use an `src` model, which would work in this case.

2018-03-09 15:00 UTC, iattempt commented
@arnavb Is this all right? I am going to merge this PR.

2018-03-09 15:04 UTC, arnavb approved these changes
Merge it! 😂

2018-03-09 16:44 UTC, merged